version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NEWS_API_KEY=your_newsapi_key
      - REACT_APP_GUARDIAN_API_KEY=your_guardian_key
      - REACT_APP_NYT_API_KEY=your_nyt_key
